// Code generated by MockGen. DO NOT EDIT.
// Source: coffeeshop.go
//
// Generated by this command:
//
//	mockgen -source=coffeeshop.go -destination=mock_coffeeshop_test.go -package=coffeeshop
//

// Package coffeeshop is a generated GoMock package.
package coffeeshop

import (
	context "context"
	coffeeshop "gopher-cafe/internal/entity/coffeeshop"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCoffeeshopUsecase is a mock of CoffeeshopUsecase interface.
type MockCoffeeshopUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockCoffeeshopUsecaseMockRecorder
	isgomock struct{}
}

// MockCoffeeshopUsecaseMockRecorder is the mock recorder for MockCoffeeshopUsecase.
type MockCoffeeshopUsecaseMockRecorder struct {
	mock *MockCoffeeshopUsecase
}

// NewMockCoffeeshopUsecase creates a new mock instance.
func NewMockCoffeeshopUsecase(ctrl *gomock.Controller) *MockCoffeeshopUsecase {
	mock := &MockCoffeeshopUsecase{ctrl: ctrl}
	mock.recorder = &MockCoffeeshopUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoffeeshopUsecase) EXPECT() *MockCoffeeshopUsecaseMockRecorder {
	return m.recorder
}

// ExecuteBrew mocks base method.
func (m *MockCoffeeshopUsecase) ExecuteBrew(ctx context.Context, orders []coffeeshop.Order, baristas int) []coffeeshop.OrderResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBrew", ctx, orders, baristas)
	ret0, _ := ret[0].([]coffeeshop.OrderResult)
	return ret0
}

// ExecuteBrew indicates an expected call of ExecuteBrew.
func (mr *MockCoffeeshopUsecaseMockRecorder) ExecuteBrew(ctx, orders, baristas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBrew", reflect.TypeOf((*MockCoffeeshopUsecase)(nil).ExecuteBrew), ctx, orders, baristas)
}

// GetStats mocks base method.
func (m *MockCoffeeshopUsecase) GetStats() (int64, int64, int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	return ret0, ret1, ret2
}

// GetStats indicates an expected call of GetStats.
func (mr *MockCoffeeshopUsecaseMockRecorder) GetStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockCoffeeshopUsecase)(nil).GetStats))
}
